### PR TITLE
general enhancements - update docs

### PR DESCRIPTION
**Pull request by engineerjoe440**
Just take a look! Nothing "stupendous" here.

Sorry about the whitespace changes, I've had better luck with 4 spaces than a single tab character.

### CODE REVIEW

**Comment by TheStaticTurtle** [comment]
Thanks, the readme looks good, but what did you exactly change in the code, I saw you, but the sample rates as a global parameter did you change anything else?

**Comment by engineerjoe440** [comment]
* [I broke out the "connection" into a `_start` method](https://github.com/TheStaticTurtle/pyVBAN/pull/8/files#diff-7a183cea83fb2fef0a48233cf997074bcf72f483c611e21ef1b6e31a869e4b29R177)
* [and I made the `runforever` method do teardown and restart during exception handling](https://github.com/TheStaticTurtle/pyVBAN/pull/8/files#diff-7a183cea83fb2fef0a48233cf997074bcf72f483c611e21ef1b6e31a869e4b29R219)
* [I also made the `PyAudio` receiver turn off its "exception on overflow" default](https://github.com/TheStaticTurtle/pyVBAN/pull/8/files#diff-7a183cea83fb2fef0a48233cf997074bcf72f483c611e21ef1b6e31a869e4b29R208)

**Comment by TheStaticTurtle** [comment]
Hi,
Sorry I took so much time to respond.

A few comments:
 - I'm not sure that the `pyaudio.PyAudio()` needs to be in the start method, as it's not actually opening anything
 - In the start method, the `inDeviceIndex` of the channel count is still the local variable

**Comment by TheStaticTurtle** [comment]
I did a big refractor, if you still want to contribute, feel free to open a new PR with ideas.
Closing this for now.

**Pull request closed without merging**
